server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hoston_user
    hikari:
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        # hibernate 不操作表结构
        ddl-auto: none
      show-sql: true